"""Auto-generated MCP server for SnapshotAPI (v1.0.0).

Generated by API2MCP from openapi3.0.
API used for snapshot testing
"""

from __future__ import annotations

import json
import logging
from typing import Any

import httpx
from mcp.server import Server
from mcp.types import TextContent, Tool

logger = logging.getLogger(__name__)

app = Server("snapshotapi")

BASE_URL = "https://api.example.com/v1"

# --- Tool Definitions ---

TOOLS: list[Tool] = [
    Tool(
        name="listitems",
        description="List items",
        inputSchema={
        "properties": {
                "page": {
                        "description": "Page number",
                        "minimum": 1,
                        "type": "integer"
                },
                "size": {
                        "description": "Page size",
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer"
                }
        },
        "type": "object"
},
    ),
    Tool(
        name="createitem",
        description="Create an item",
        inputSchema={
        "properties": {
                "name": {
                        "description": "Item name",
                        "type": "string"
                },
                "value": {
                        "description": "Item value",
                        "type": "number"
                }
        },
        "required": [
                "name"
        ],
        "type": "object"
},
    ),
    Tool(
        name="getitem",
        description="Get an item by ID",
        inputSchema={
        "properties": {
                "itemId": {
                        "description": "The item ID",
                        "type": "string"
                }
        },
        "required": [
                "itemId"
        ],
        "type": "object"
},
    ),
]


@app.list_tools()
async def list_tools() -> list[Tool]:
    """Return all available tools."""
    return TOOLS


@app.call_tool()
async def call_tool(name: str, arguments: dict[str, Any]) -> list[TextContent]:
    """Route tool calls to handlers."""
    _handlers = {
        "listitems": _handle_listitems,
        "createitem": _handle_createitem,
        "getitem": _handle_getitem,
    }

    async with httpx.AsyncClient(base_url=BASE_URL) as client:
        handler = _handlers.get(name)
        if handler is not None:
            result = await handler(arguments, client)
        else:
            result = json.dumps({"error": f"Unknown tool: {name}"})

    return [TextContent(type="text", text=result)]


# --- Tool Handlers ---

async def _handle_listitems(
    args: dict[str, Any],
    client: httpx.AsyncClient,
) -> str:
    """List items"""
    path = "/items"

    params: dict[str, Any] = {}
    if "page" in args:
        params["page"] = args["page"]
    if "size" in args:
        params["size"] = args["size"]

    headers: dict[str, str] = {}

    response = await client.request("get", path, params=params or None, headers=headers or None)

    response.raise_for_status()
    if response.headers.get("content-type", "").startswith("application/json"):
        return json.dumps(response.json(), indent=2)
    return response.text or f"Status: {response.status_code}"

async def _handle_createitem(
    args: dict[str, Any],
    client: httpx.AsyncClient,
) -> str:
    """Create an item"""
    path = "/items"

    params: dict[str, Any] = {}

    headers: dict[str, str] = {}

    body_keys = ["name", "value"]
    json_body = {k: args[k] for k in body_keys if k in args}
    response = await client.request("post", path, params=params or None, headers=headers or None, json=json_body or None)

    response.raise_for_status()
    if response.headers.get("content-type", "").startswith("application/json"):
        return json.dumps(response.json(), indent=2)
    return response.text or f"Status: {response.status_code}"

async def _handle_getitem(
    args: dict[str, Any],
    client: httpx.AsyncClient,
) -> str:
    """Get an item by ID"""
    path = "/items/{itemId}"
    if "itemId" in args:
        path = path.replace("{itemId}", str(args["itemId"]))

    params: dict[str, Any] = {}

    headers: dict[str, str] = {}

    response = await client.request("get", path, params=params or None, headers=headers or None)

    response.raise_for_status()
    if response.headers.get("content-type", "").startswith("application/json"):
        return json.dumps(response.json(), indent=2)
    return response.text or f"Status: {response.status_code}"
